# Notebook Title

## Setup Python and R environment
you can ignore this section

In [2]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (16, 100)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

In [3]:
%%javascript
// Disable auto-scrolling
IPython.OutputArea.prototype._should_scroll = function(lines) {
    return false;
}

In [4]:
%%R

# My commonly used R imports

require('tidyverse')

â”€â”€ Attaching core tidyverse packages â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse 2.0.0 â”€â”€
âœ” dplyr     1.1.4     âœ” readr     2.1.5
âœ” forcats   1.0.0     âœ” stringr   1.5.1
âœ” ggplot2   3.4.4     âœ” tibble    3.2.1
âœ” lubridate 1.9.3     âœ” tidyr     1.3.1
âœ” purrr     1.0.2
â”€â”€ Conflicts â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ tidyverse_conflicts() â”€â”€
âœ– dplyr::filter() masks stats::filter()
âœ– dplyr::lag()    masks stats::lag()
â„¹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Loading required package: tidyverse

## ðŸ‘‰ download your data

You can write code here to download your dataset. Or if you already have it, just leave the URL in the comments and just load it into a pandas or R (or both) dataframe.

In [5]:
import pandas as pd

In [27]:

df = pd.read_csv('bilingual.csv')
df['School'].value_counts()

School
75K721    7
24Q013    5
15K094    4
31R022    4
07X025    4
         ..
12X550    1
12X463    1
12X214    1
12X196    1
79Q950    1
Name: count, Length: 376, dtype: int64

## ðŸ‘‰ convert addresses --> lat/long 

See the [census-examples](https://github.com/data4news/census-examples) repository for examples. If you need help, try asking in the class slack channel. Chances are someone in the class is struggling with the same problem as you are so we might as well all learn together in the same slack channel!

In [33]:
add = pd.read_csv('locations.csv')
add

,fiscal_year,system_code,location_code,location_name,BEDS,Managed_by_name,location_type_description,Location_Category_Description,Grades_text,Grades_final_text,...,Administrative_District_Name,community_school_sup_name,Tier_3_Support_Location_Name,Tier_3_Support_Leader_Name,Tier_2_Support_Location_Name,HighSchool_Network_Location_Code,HighSchool_Network_Name,HighSchool_Network_Superintendent,Community_district 1,Police_precinct
0,2020,15K001,K001,P.S. 001 The Bergen,331500010001,DOE,General Academic,Elementary,"PK,0K,01,02,03,04,05,SE","PK,0K,01,02,03,04,05",...,COMMUNITY SCHOOL DISTRICT 15,"SKOP, ANITA",NYCDOE Borough Office - Brooklyn North,NaN,School Support Team 5- Brooklyn North,NaN,NaN,NaN,307.0,72.0
1,2020,17K002,K002,Parkside Preparatory Academy,331700010002,DOE,General Academic,Junior High-Intermediate-Middle,"06,07,08,SE","06,07,08",...,COMMUNITY SCHOOL DISTRICT 17,"ELLIS, CLARENCE",NYCDOE Borough Office - Brooklyn South,Mauriciere de Govia,School Support Team 2- Brooklyn South,NaN,NaN,NaN,309.0,71.0
2,2020,13K003,K003,P.S. 003 The Bedford Village,331300010003,DOE,General Academic,Elementary,"PK,0K,01,02,03,04,05,SE","PK,0K,01,02,03,04,05",...,COMMUNITY SCHOOL DISTRICT 13,"SAMUELS, KAMAR",NYCDOE Borough Office - Brooklyn North,NaN,School Support Team 3- Brooklyn North,NaN,NaN,NaN,303.0,79.0
3,2020,75K004,K004,P.S. K004,307500013004,DOE,Special Education,Elementary,"PK,0K,01,02,03,04,05,SE","PK,0K,01,02,03,04,05,06,07,SE",...,CITYWIDE SPECIAL EDUCATION,"LOUISSAINT, KETLER",D75 CITYWIDE BCO,Tillman Roberto,Children First Network 752,NaN,NaN,NaN,305.0,75.0
4,2020,16K005,K005,P.S. 005 Dr. Ronald McNair,331600010005,DOE,General Academic,Elementary,"PK,0K,01,02,03,04,05,SE","PK,0K,01,02,03,04,05",...,COMMUNITY SCHOOL DISTRICT 16,"MARTIN, YOLANDA",NYCDOE Borough Office - Brooklyn North,NaN,School Support Team 4- Brooklyn North,NaN,NaN,NaN,303.0,81.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2185,2020,84X729,X729,Readnet Bronx Charter School,320700860842,Charter,General Academic,Elementary,"01,02",NaN,...,OFFICE OF CHARTER SCHOOLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201.0,40.0
2186,2020,84X730,X730,Bronx Charter School for the Arts,320800860846,Charter,General Academic,Elementary,"0K,01,02,03,04,05,06,07","0K,01,02,03,04,05,06,07,08",...,OFFICE OF CHARTER SCHOOLS,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202.0,41.0
2187,2020,75X754,X754,J. M. Rapport School Career Development,307500012754,DOE,Special Education,High school,"09,10,11,12,SE","09,10,11,12,SE",...,CITYWIDE SPECIAL EDUCATION,"LOUISSAINT, KETLER",D75 CITYWIDE BCO,Tillman Roberto,Children First Network 755,NaN,NaN,NaN,201.0,40.0
2188,2020,75X811,X811,P.S. X811,307500012811,DOE,Special Education,Secondary School,"08,09,10,11,12,SE","07,08,09,10,11,12,SE",...,CITYWIDE SPECIAL EDUCATION,"LOUISSAINT, KETLER",D75 CITYWIDE BCO,Tillman Roberto,Children First Network 755,NaN,NaN,NaN,203.0,42.0
2189,2020,75X811,X811,P.S. X811,307500012811,DOE,Special Education,Secondary School,"08,09,10,11,12,SE","07,08,09,10,11,12,SE",...,CITYWIDE SPECIAL EDUCATION,"LOUISSAINT, KETLER",D75 CITYWIDE BCO,Tillman Roberto,Children First Network 755,NaN,NaN,NaN,203.0,42.0

In [36]:
# merge df and add where df key is 'School' and add key is 'system_code'

df_merge = pd.merge(df, add, left_on='School', right_on='system_code', how='left')
df_merge

,Borough,Borough/Citywide Office (B/CO),District,School,School Name,School Category,Program,Language,Language (Translated),General/Special Education,...,Administrative_District_Name,community_school_sup_name,Tier_3_Support_Location_Name,Tier_3_Support_Leader_Name,Tier_2_Support_Location_Name,HighSchool_Network_Location_Code,HighSchool_Network_Name,HighSchool_Network_Superintendent,Community_district 1,Police_precinct
0,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,COMMUNITY SCHOOL DISTRICT 01,"CHAN, CARRY",NYCDOE Borough Office - Manhattan,"CHU, YUET",School Support Team 3- Manhattan,NaN,NaN,NaN,103.0,7.0
1,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Spanish,EspaÃ±ol,General Education,...,COMMUNITY SCHOOL DISTRICT 01,"CHAN, CARRY",NYCDOE Borough Office - Manhattan,"CHU, YUET",School Support Team 3- Manhattan,NaN,NaN,NaN,103.0,7.0
2,Manhattan,Manhattan,1,01M184,P.S. 184m Shuang Wen,K-8,Dual Language,Chinese,ä¸­æ–‡,General Education,...,COMMUNITY SCHOOL DISTRICT 01,"CHAN, CARRY",NYCDOE Borough Office - Manhattan,"CHU, YUET",School Support Team 3- Manhattan,NaN,NaN,NaN,103.0,7.0
3,Manhattan,Manhattan,1,01M184,P.S. 184m Shuang Wen,K-8,Dual Language,Chinese,ä¸­æ–‡,Special Education,...,COMMUNITY SCHOOL DISTRICT 01,"CHAN, CARRY",NYCDOE Borough Office - Manhattan,"CHU, YUET",School Support Team 3- Manhattan,NaN,NaN,NaN,103.0,7.0
4,Manhattan,Manhattan,1,01M188,P.S. 188 The Island School,K-8,Dual Language,Spanish,EspaÃ±ol,General Education,...,COMMUNITY SCHOOL DISTRICT 01,"CHAN, CARRY",NYCDOE Borough Office - Manhattan,"CHU, YUET",School Support Team 3- Manhattan,NaN,NaN,NaN,103.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
551,Bronx,District 75,75,75X811,P.S. X811,Secondary School,Transitional Bilingual Education,Spanish,EspaÃ±ol,Special Education,...,CITYWIDE SPECIAL EDUCATION,"LOUISSAINT, KETLER",D75 CITYWIDE BCO,Tillman Roberto,Children First Network 755,NaN,NaN,NaN,203.0,42.0
552,Bronx,District 75,75,75X811,P.S. X811,Secondary School,Transitional Bilingual Education,Spanish,EspaÃ±ol,Special Education,...,CITYWIDE SPECIAL EDUCATION,"LOUISSAINT, KETLER",D75 CITYWIDE BCO,Tillman Roberto,Children First Network 755,NaN,NaN,NaN,203.0,42.0
553,Bronx,District 75,75,75X811,P.S. X811,Secondary School,Transitional Bilingual Education,Spanish,EspaÃ±ol,Special Education,...,CITYWIDE SPECIAL EDUCATION,"LOUISSAINT, KETLER",D75 CITYWIDE BCO,Tillman Roberto,Children First Network 755,NaN,NaN,NaN,203.0,42.0
554,Manhattan,ACCESS,79,79M973,Restart Academy,Ungraded,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
555,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df_merge.columns

Index(['Borough', 'Borough/Citywide Office (B/CO)', 'District', 'School',
       'School Name', 'School Category', 'Program', 'Language',
       'Language (Translated)', 'General/Special Education',
       'Special Education Model', 'fiscal_year', 'system_code',
       'location_code', 'location_name', 'BEDS', 'Managed_by_name',
       'location_type_description', 'Location_Category_Description',
       'Grades_text', 'Grades_final_text', 'open_date', 'Status_descriptions',
       'Primary_building_code', 'primary_address_line_1', 'State_code',
       'X_COORDINATE', 'Y_COORDINATE', 'LONGITUDE', 'LATITUDE',
       'Community_district', 'Council-district', 'Census_tract',
       'Borough_block_lot', 'NTA', 'NTA_Name', 'Principal_Name',
       'Principal_title', 'Principal_phone_number', 'fax_number',
       'Geographical_District_code', 'Administrative_District_Code',
       'Administrative_District_Name', 'community_school_sup_name',
       'Tier_3_Support_Location_Name', 'Tier_3_Support_Leader_Name',
       'Tier_2_Support_Location_Name', 'HighSchool_Network_Location_Code',
       'HighSchool_Network_Name', 'HighSchool_Network_Superintendent',
       'Community_district 1', 'Police_precinct'],
      dtype='object')

## ðŸ‘‰ convert lat/long to census geography codes 

(like 'GEOID', 'STATE', 'COUNTY', 'TRACT', 'BLOCK', etc...)

Same note as above, see [census-examples](https://github.com/data4news/census-examples) repository for examples or ask in the class slack channel if stuck.

In [41]:
import glob
import json
import requests
import pandas as pd
from pprint import pprint

In [43]:
# datamade's Census package
from census import Census

In [44]:
c = Census("2b439405843d7c5b73d408bf38e100d4bb36ea87")

In [46]:
dem = pd.read_csv('demographics.csv')
dem

,DBN,School Name,Year,Total Enrollment,Grade 3K+PK (Half Day & Full Day),Grade K,Grade 1,Grade 2,Grade 3,Grade 4,...,% White,# Missing Race/Ethnicity Data,% Missing Race/Ethnicity Data,# Students with Disabilities,% Students with Disabilities,# English Language Learners,% English Language Learners,# Poverty,% Poverty,Economic Need Index
0,01M015,P.S. 015 Roberto Clemente,2016-17,178,17,28,33,27,31,24,...,0.022000,0,0.000000,51,0.287000,12,0.067,152,85.4%,88.2%
1,01M015,P.S. 015 Roberto Clemente,2017-18,190,17,28,32,33,23,31,...,0.032000,0,0.000000,49,0.258000,8,0.042,161,84.7%,89.0%
2,01M015,P.S. 015 Roberto Clemente,2018-19,174,13,20,33,30,30,20,...,0.034000,0,0.000000,39,0.224000,8,0.046,147,84.5%,88.8%
3,01M015,P.S. 015 Roberto Clemente,2019-20,190,14,29,28,38,33,29,...,0.047000,0,0.000000,46,0.242000,17,0.089,155,81.6%,86.7%
4,01M015,P.S. 015 Roberto Clemente,2020-21,193,17,29,29,27,30,32,...,0.057000,0,0.000000,43,0.223000,21,0.109,158,81.9%,85.6%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9164,84X730,Bronx Charter School for the Arts,2016-17,320,0,53,53,55,52,53,...,0.009375,0,0.000000,67,0.209375,51,0.159,235,73.4%,84.0%
9165,84X730,Bronx Charter School for the Arts,2017-18,314,0,50,51,54,51,52,...,0.003185,0,0.000000,68,0.216561,57,0.182,258,82.2%,89.1%
9166,84X730,Bronx Charter School for the Arts,2018-19,430,0,49,54,49,54,51,...,0.006977,0,0.000000,103,0.239535,71,0.165,363,84.4%,88.8%
9167,84X730,Bronx Charter School for the Arts,2019-20,523,0,51,50,53,52,55,...,0.009560,0,0.000000,117,0.223709,69,0.132,453,86.6%,89.2%
9168,84X730,Bronx Charter School for the Arts,2020-21,626,0,38,52,53,55,55,...,0.006390,1,0.001597,153,0.244409,78,0.125,541,86.4%,88.2%

In [49]:
df_merge2 = pd.merge(df_merge, dem, left_on='School', right_on='DBN', how='left')
df_merge2

,Borough,Borough/Citywide Office (B/CO),District,School,School Name_x,School Category,Program,Language,Language (Translated),General/Special Education,...,% White,# Missing Race/Ethnicity Data,% Missing Race/Ethnicity Data,# Students with Disabilities,% Students with Disabilities,# English Language Learners,% English Language Learners,# Poverty,% Poverty,Economic Need Index
0,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.050,0,0.000,116,0.215,93,0.172,315,58.3%,67.7%
1,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.032,1,0.002,118,0.237,86,0.173,366,73.6%,80.0%
2,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.046,1,0.002,117,0.243,63,0.131,326,67.8%,75.4%
3,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.067,1,0.002,106,0.228,61,0.131,354,76.3%,78.4%
4,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.073,1,0.002,90,0.218,49,0.119,292,70.9%,76.2%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2757,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.054,0,0.000,410,0.107,542,0.141,1569,40.9%,72.0%
2758,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.050,0,0.000,400,0.113,473,0.134,2607,73.9%,88.3%
2759,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.052,0,0.000,469,0.132,547,0.154,2597,73.1%,87.8%
2760,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.048,0,0.000,449,0.128,565,0.161,2629,74.9%,91.2%
2761,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.059,0,0.000,537,0.160,539,0.161,2634,78.6%,90.6%

In [51]:
df_merge2['Census_tract']

0       3001.0
1       3001.0
2       3001.0
3       3001.0
4       3001.0
         ...
2757       NaN
2758       NaN
2759       NaN
2760       NaN
2761       NaN
Name: Census_tract, Length: 2762, dtype: float64

In [52]:
df_merge2['Census_tract'].value_counts()

Census_tract
40900.0    80
25100.0    45
27700.0    45
48500.0    40
30800.0    40
           ..
27400.0     5
22702.0     5
18400.0     5
46201.0     3
1003.0      2
Name: count, Length: 262, dtype: int64

## ðŸ‘‰ Output Data

Output your dataframe containing your data and the Census connector codes (like tract, block, etc...).

In [53]:
df_merge2

,Borough,Borough/Citywide Office (B/CO),District,School,School Name_x,School Category,Program,Language,Language (Translated),General/Special Education,...,% White,# Missing Race/Ethnicity Data,% Missing Race/Ethnicity Data,# Students with Disabilities,% Students with Disabilities,# English Language Learners,% English Language Learners,# Poverty,% Poverty,Economic Need Index
0,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.050,0,0.000,116,0.215,93,0.172,315,58.3%,67.7%
1,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.032,1,0.002,118,0.237,86,0.173,366,73.6%,80.0%
2,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.046,1,0.002,117,0.243,63,0.131,326,67.8%,75.4%
3,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.067,1,0.002,106,0.228,61,0.131,354,76.3%,78.4%
4,Manhattan,Manhattan,1,01M020,P.S. 020 Anna Silver,Elementary,Dual Language,Chinese,ä¸­æ–‡,General Education,...,0.073,1,0.002,90,0.218,49,0.119,292,70.9%,76.2%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2757,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.054,0,0.000,410,0.107,542,0.141,1569,40.9%,72.0%
2758,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.050,0,0.000,400,0.113,473,0.134,2607,73.9%,88.3%
2759,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.052,0,0.000,469,0.132,547,0.154,2597,73.1%,87.8%
2760,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.048,0,0.000,449,0.128,565,0.161,2629,74.9%,91.2%
2761,Queens,ACCESS,79,79Q950,Pathways to Graduation,High school,Transitional Bilingual Education,Spanish,EspaÃ±ol,General Education,...,0.059,0,0.000,537,0.160,539,0.161,2634,78.6%,90.6%

In [54]:
df_merge2.to_csv('output.csv', index=False)